void PlayBattleAnim(void);
void v_PlayBattleAnim(void);
void BattleAnimRunScript(void);
void RunBattleAnimScript(void);
void BattleAnimClearHud(void);
void BattleAnimRestoreHuds(void);
void BattleAnimRequestPals(void);
void BattleAnimDelayFrame(void);
void ClearActorHud(void);
void PlaceWindowOverBattleTextbox(void);
void BattleAnim_ClearOAM(void);
void RunBattleAnimCommand(void);
// void BattleAnimCommands(void);
void BattleAnimCmd_Wait(uint8_t a);
void BattleAnimCmd_EA(void);
void BattleAnimCmd_EB(void);
void BattleAnimCmd_EC(void);
void BattleAnimCmd_ED(void);
void BattleAnimCmd_Ret(battleanim_s* anim);
void BattleAnimCmd_Call(battleanim_s* anim, battleanim_func func);
void BattleAnimCmd_Jump(battleanim_s* anim, battleanim_func func);
void BattleAnimCmd_Loop(battleanim_s* anim, uint8_t count, battleanim_func func);
bool BattleAnimCmd_LoopInline(uint8_t count);
void BattleAnimCmd_JumpUntil(battleanim_s* anim, battleanim_func func);
void BattleAnimCmd_SetVar(uint8_t var);
void BattleAnimCmd_IncVar(void);
void BattleAnimCmd_IfVarEqual(battleanim_s* anim, uint8_t n, battleanim_func func);
void BattleAnimCmd_IfParamEqual(battleanim_s* anim, uint8_t param, battleanim_func func);
void BattleAnimCmd_IfParamAnd(battleanim_s* anim, uint8_t n, battleanim_func func);
void BattleAnimCmd_Obj(uint8_t index, uint8_t x, uint8_t y, uint8_t param);
void BattleAnimCmd_BGEffect(uint8_t index, uint8_t jt, uint8_t turn, uint8_t param);
void BattleAnimCmd_BGP(uint8_t bgp);
void BattleAnimCmd_OBP0(uint8_t obp0);
void BattleAnimCmd_OBP1(uint8_t obp1);
void BattleAnimCmd_ResetObp0(void);
void BattleAnimCmd_ClearObjs(void);
void BattleAnimCmd_1GFX(void);
void BattleAnimCmd_2GFX(void);
void BattleAnimCmd_3GFX(void);
void BattleAnimCmd_4GFX(void);
void BattleAnimCmd_5GFX(void);
void BattleAnimCmd_NGFX(unsigned int c, ...);
void BattleAnimCmd_IncObj(uint8_t a);
void BattleAnimCmd_IncBGEffect(uint8_t c);
void BattleAnimCmd_SetObj(uint8_t a, uint8_t jt);
void BattleAnimCmd_BattlerGFX_1Row(void);
void BattleAnimCmd_BattlerGFX_1Row(void);
void BattleAnimCmd_BattlerGFX_2Row(void);
void BattleAnimCmd_BattlerGFX_2Row(void);
void BattleAnimCmd_CheckPokeball(void);
void BattleAnimCmd_E7(void);
void BattleAnimCmd_Transform(void);
void BattleAnimCmd_UpdateActorPic(void);
void BattleAnimCmd_RaiseSub(void);
void GetSubstitutePic(void);
void BattleAnimCmd_MinimizeOpp(void);
// void GetMinimizePic(void);
// void CopyMinimizePic(uint8_t* de);
// extern const char MinimizePic[];
void BattleAnimCmd_Minimize(void);
void BattleAnimCmd_DropSub(void);
void BattleAnimCmd_BeatUp(void);
void BattleAnimCmd_OAMOn(void);
void BattleAnimCmd_OAMOff(void);
void BattleAnimCmd_KeepSprites(void);
void BattleAnimCmd_F5(void);
void BattleAnimCmd_F6(void);
void BattleAnimCmd_F7(void);
void BattleAnimCmd_Sound(uint8_t duration, uint8_t tracks, uint16_t sfx);
void BattleAnimCmd_Cry(uint8_t cry);
void PlayHitSound(void);
void BattleAnimAssignPals(void);
void ClearBattleAnims(void);
void BattleAnim_RevertPals(void);
void BattleAnim_SetBGPals(uint8_t bgp);
void BattleAnim_SetOBPals(uint8_t obp0);
void BattleAnim_UpdateOAM_All(void);
//#include "gfx/battle/minimize.2bpp"
